### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by PKWadsy** [PilloFoundation/duvet#7]
For anyone to trust the project, it will need high test coverage. For this reason, I would like to start using `jest --cover` and write more tests to get at least 95% coverage

**Comment by joshuabrownenz** [comment]
I would recommend using codecov.io to provide commit, branch and PR diff coverage targets.

**Comment by PKWadsy** [comment]
Codecov.io is not being used. Just need to get the coverage up haha

**Comment by PKWadsy** [comment]
Above 90% now. Still need to get it above 95%

**Comment by PKWadsy** [comment]
We now have 100% coverage yay!
